[package]
name = "kaudio"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
clap = {version = "4.5.18", features = ["derive"]}
cpal = {version = "0.15.3"}
log = "0.4.22"
log4rs = "1.3.0"

[features]
jack = []
